[package]

name = "quall"
description = "A consensus datastore for the people; spaghetti and meatballs"
version = "0.0.1"
authors = [
  "Tyler Neely <t@jujit.su>",
  "Steve Salevan <steve.salevan@gmail.com>"
]
license = "Apache-2.0"